# Generated by Django 3.2.3 on 2021-05-18 12:47

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20210518_1227"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", users.models.UserManager()),
            ],
        ),
    ]
